"""FR5 — the serving layer.

Reads only the pre-aggregated Parquet exported by src/export.py. There is no
DuckDB file here and no raw data: the app's whole job is to display numbers
that were computed offline, plus one live call to the LLM layer.
"""
from __future__ import annotations

import sys
from pathlib import Path

import polars as pl
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

import llm  # noqa: E402
from queries import MIN_TESTS_FOR_CONFIDENCE, VehicleProfile  # noqa: E402

DATA = Path(__file__).resolve().parent.parent / "data" / "processed"

st.set_page_config(page_title="MOTIntel", page_icon="🚗", layout="wide")


@st.cache_data
def load(name: str) -> pl.DataFrame:
    return pl.read_parquet(DATA / name)


@st.cache_data
def summarise_cached(make: str, model: str, age: int, n: int,
                     rate: float, defects: list, mileage: list) -> str | None:
    """Cached across users and reruns (FR4.5). Arguments are plain values so
    Streamlit can hash them."""
    profile = VehicleProfile(make=make, model=model, age_years=age, n_tests=n,
                             failure_rate=rate, top_defects=defects,
                             by_mileage=mileage)
    return llm.summarise(profile)


st.title("MOTIntel")
st.caption("UK vehicle reliability, from 42.7 million real MOT tests")

try:
    models = load("models.parquet")
    rates = load("failure_rates.parquet")
    defects = load("top_defects.parquet")
except FileNotFoundError:
    st.error("Serving data not found. Run `python src/export.py` first.")
    st.stop()

# --- FR5.1 selection -------------------------------------------------------
c1, c2, c3 = st.columns([2, 3, 2])
make = c1.selectbox("Make", sorted(models["make"].unique().to_list()))
model_options = (models.filter(pl.col("make") == make)
                 .sort("n_tests", descending=True)["model"].to_list())
model = c2.selectbox("Model", model_options)
age = c3.slider("Vehicle age at test (years)", 3, 25, 8)

age_band = (age // 3) * 3
cells = rates.filter((pl.col("make") == make) & (pl.col("model") == model)
                     & (pl.col("age_band") == age_band))

if cells.is_empty():
    st.warning(f"No data for a {age}-year-old {make} {model} in this dataset.")
    st.stop()

n_tests = int(cells["n_tests"].sum())
failure_rate = float(
    (cells["failure_rate"] * cells["n_tests"]).sum() / n_tests)

# --- FR5.2 headline --------------------------------------------------------
m1, m2, m3 = st.columns(3)
m1.metric("Failure probability", f"{failure_rate:.0%}")
m2.metric("Tests in this group", f"{n_tests:,}")
sparse = n_tests < MIN_TESTS_FOR_CONFIDENCE
m3.metric("Confidence", "Low" if sparse else "Good",
          help=f"Based on {n_tests:,} tests. Below "
               f"{MIN_TESTS_FOR_CONFIDENCE} the figure is unreliable.")
if sparse:
    st.warning("Too few tests in this group to be confident in the figure.")

# --- FR5.6 the AI summary --------------------------------------------------
st.subheader("What this means")
top = (defects.filter((pl.col("make") == make) & (pl.col("model") == model)
                      & (pl.col("age_band") == age_band))
       .sort("n_tests", descending=True).head(10))
by_mileage = (cells.sort("mileage_band")
              .select(mileage_band=pl.col("mileage_band"),
                      n_tests=pl.col("n_tests"),
                      failure_rate=pl.col("failure_rate")))

if not llm.credentials_available():
    st.info("AI summary unavailable — no Claude API credentials configured. "
            "The figures below are unaffected.")
else:
    with st.spinner("Reading the defect data ..."):
        summary = summarise_cached(
            make, model, age, n_tests, failure_rate,
            top.rename({"defect_category": "category",
                        "defect_desc": "defect"}).to_dicts(),
            [{"mileage_band": f"{r['mileage_band'] // 1000}k",
              "n_tests": r["n_tests"], "failure_rate": r["failure_rate"]}
             for r in by_mileage.to_dicts()])
    if summary:
        st.write(summary)
        st.caption("Generated by Claude from the retrieved figures on this "
                   "page only. No other vehicle information is used.")
    else:
        # FR4.4 — the layer is down, the page still works.
        st.info("AI summary unavailable right now. The figures below are "
                "unaffected.")

# --- FR5.3 / FR5.4 charts --------------------------------------------------
left, right = st.columns(2)
with left:
    st.subheader("What fails most")
    if top.is_empty():
        st.caption("No defect breakdown for this group.")
    else:
        st.bar_chart(
            top.select(pl.col("defect_desc").alias("defect"),
                       pl.col("share_of_tests").alias("share of tests"))
               .to_pandas().set_index("defect"))
with right:
    st.subheader("Failure rate by mileage")
    st.bar_chart(
        by_mileage.select(
            pl.col("mileage_band").cast(pl.Utf8).alias("miles"),
            pl.col("failure_rate").alias("failure rate"))
        .to_pandas().set_index("miles"))

# --- FR5.5 peers -----------------------------------------------------------
st.subheader("Compared with other models of the same age")
peers = (rates.filter((pl.col("age_band") == age_band)
                      & ~((pl.col("make") == make) & (pl.col("model") == model)))
         .group_by("make", "model")
         .agg(n_tests=pl.col("n_tests").sum(),
              failure_rate=(pl.col("failure_rate") * pl.col("n_tests")).sum()
                           / pl.col("n_tests").sum())
         .sort("n_tests", descending=True).head(5))
st.dataframe(peers.to_pandas(), hide_index=True, use_container_width=True)

# --- FR5.7 provenance ------------------------------------------------------
st.divider()
st.caption(
    "Source: DVSA anonymised MOT testing data, 2025 (42.7 million tests). "
    "Contains public sector information licensed under the Open Government "
    "Licence v3.0. An MOT failure rate is not a reliability rating: the test "
    "covers safety and emissions items at one annual point, cannot see repairs "
    "made between tests, and reflects owner maintenance as much as build "
    "quality.")
